### ISSUE TITLE
Icons are missing from the img

### ISSUE THREAD

**Issue by sirlisko** [cedmax/marked-safe#1]
![marked-safe](https://cloud.githubusercontent.com/assets/435399/24543822/e3543b40-15f8-11e7-85d3-a9e73c81c274.jpg)

**Comment by cedmax** [comment]
Good catch, I need to double check if it's a cross domain problem or an htm2canvas issue (as for the box shadow, for example): I can't fix the latter, but I can surely tackle moving the needed icons on my domain

**Comment by cedmax** [comment]
fixed
